# Generated by Django 6.0.3 on 2026-03-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurants_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'menuItems'},
        ),
        migrations.AlterModelOptions(
            name='menuitemvariants',
            options={'ordering': ['price'], 'verbose_name_plural': 'MenuItemsVariants'},
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
    ]
