# Generated by Django 6.0.3 on 2026-03-22 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_menuitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='avg_delivery_time',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='delivery_fee',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='avg_preparing_time',
            field=models.PositiveIntegerField(default=10, help_text='Average Food preparing time in minutes', verbose_name='Preparing Time in minutes'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='if true,the restro is  subsidized , zero delivery fee+premium section on app', verbose_name='Premium Restaurant'),
        ),
        migrations.AddIndex(
            model_name='restaurants',
            index=models.Index(fields=['is_premium'], name='restaurants_is_prem_f8b5e4_idx'),
        ),
    ]
