# Generated by Django 6.0.3 on 2026-03-21 20:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_alter_menuitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='cartId')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UpdatedAt')),
                ('customer', models.OneToOneField(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('restaurant', models.ForeignKey(limit_choices_to={'role': 'RESTAURANT_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.restaurants', verbose_name='Restaurants')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='orderId')),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLACED', max_length=20, verbose_name='Status')),
                ('delivery_address', models.TextField()),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Delivery Latitude')),
                ('delivery_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Delivery Longitude')),
                ('payment_method', models.CharField(choices=[('COD', 'Cash On Delivery'), ('UPI', 'UPI Payment Gateway'), ('CARD', 'Credit/Debit Card'), ('NETBANKING', 'Net Banking')], default='COD', max_length=20, verbose_name='Payment Method')),
                ('payment_provider', models.CharField(choices=[('NONE', 'None'), ('RAZORPAY', 'Razorpay')], default='NONE', max_length=20, verbose_name='Payment Provider')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Total Amount')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Delivery Fee')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Total Amount')),
                ('cancelled_by', models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('RESTAURANT', 'Restaurant'), ('SYSTEM', 'System')], max_length=20, null=True, verbose_name='Cancelled By')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation Reason')),
                ('placed_at', models.DateTimeField(auto_now_add=True, verbose_name='Placed At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('customer_note', models.TextField(blank=True, null=True, verbose_name='Customer Note')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('delivery_agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'DELIVERY_AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Delivery Agent')),
                ('restaurant', models.ForeignKey(limit_choices_to={'role': 'RESTAURANT_OWNER'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.restaurants', verbose_name='Restaurant')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name_plural': 'Order Status Histories',
                'db_table': 'order_status_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem', verbose_name='Menu Item')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.menuitemvariants', verbose_name='Menu Item Variant')),
            ],
            options={
                'unique_together': {('cart', 'menu_item', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('item_name', models.CharField(max_length=250, verbose_name='Item Name')),
                ('variant_name', models.CharField(blank=True, max_length=100, verbose_name='Variant Name')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Price at Order Time')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.menuitem', verbose_name='Menu Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.menuitemvariants', verbose_name='Menu Item Variant')),
            ],
            options={
                'unique_together': {('order', 'menu_item', 'variant')},
            },
        ),
    ]
