# Generated by Django 6.0.3 on 2026-03-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_unit_price_orderitem_price_and_more'),
        ('restaurants', '0004_remove_restaurants_avg_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='restaurants.restaurants', verbose_name='Restaurants'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.restaurants', verbose_name='Restaurant'),
        ),
    ]
